version: "3"
networks:
  lnmp-net:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mariadb/db:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/mariadb.conf.d
      - ./mariadb/logs:/var/log/mysql
    restart: always
    networks:
      - lnmp-net
  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      - 8080:80
    volumes:
      - ./www:/usr/share/nginx/html:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    command: chown -R www-data:www-data /usr/share/nginx/html
    depends_on:
      - mariadb
      - redis
      - php
    restart: always
    networks:
      - lnmp-net
  php:
    container_name: php
    image: registry.cn-qingdao.aliyuncs.com/bartoncheng/ysphp:1.0-release
    volumes:
      - ./www:/usr/share/nginx/html:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/logs:/usr/local/var/log
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    networks:
      - lnmp-net
  redis:
    container_name: redis
    image: redis:5.0.7
    ports:
      - 6380:6379
    volumes:
      - ./redis/db:/var/lib/redis
      - ./redis/logs:/var/log/redis
    restart: always
    networks:
      - lnmp-net
