version: "3"
networks:
  lnmp-net:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /data/mariadb/db:/var/lib/mysql
      - /data/mariadb/conf.d:/etc/mysql/mariadb.conf.d
      - /data/mariadb/logs:/var/log/mysql
    restart: always
    networks:
      - lnmp-net
  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      - 8080:80
      - 4433:443
    volumes:
      - /data/www:/usr/share/nginx/html
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/logs:/var/log/nginx
    depends_on:
      - mariadb
      - redis
      - php
    restart: always
    networks:
      - lnmp-net
  php:
    container_name: php
    image: ysphp:7.4-fpm
    volumes:
      - /data/www:/usr/share/nginx/html
      - /data/php/php.ini:/usr/local/etc/php/php.ini
      - /data/php/logs:/usr/local/var/log
      - /data/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    networks:
      - lnmp-net
  redis:
    container_name: redis
    image: redis:5.0.7
    ports:
      - 6380:6379
    volumes:
      - /data/redis/db:/var/lib/redis
      - /data/redis/logs:/var/log/redis
    restart: always
    networks:
      - lnmp-net
